USE SUPER_NLP;

IF NOT EXISTS (
		SELECT *
		FROM sys.indexes
		WHERE object_id = object_id('[ORDER_RES_COMP_CMT]')
			AND NAME = 'IDX_NOTES'
		)
BEGIN
	CREATE CLUSTERED INDEX IDX_NOTES ON ORDER_RES_COMP_CMT (
		ORDER_ID
		,PAT_ID
		,COMPONENT_ID
		)
END

IF NOT EXISTS (
		SELECT *
		FROM sys.indexes
		WHERE object_id = object_id('[ORDER_RES_COMP_CMT]')
			AND NAME = 'IDX_ORDERING_DATE'
		)
BEGIN
	CREATE NONCLUSTERED INDEX IDX_ORDERING_DATE ON ORDER_RES_COMP_CMT (ORDER_ID) INCLUDE (
		ORDERING_DATE
		,PAT_ID
		,COMPONENT_ID
		)
END

IF NOT EXISTS (
		SELECT *
		FROM sys.indexes
		WHERE object_id = object_id('[HNO_NOTE_TEXT]')
			AND NAME = 'IDX_NOTES'
		)
BEGIN
	CREATE CLUSTERED INDEX IDX_NOTES ON SUPER_NLP.dbo.HNO_NOTE_TEXT (
		PAT_ID
		,PAT_ENC_CSN_ID
		,NOTE_ID
		)
END

IF NOT EXISTS (
		SELECT *
		FROM sys.indexes
		WHERE object_id = object_id('[HNO_NOTE_TEXT]')
			AND NAME = 'IDX_CONTACT_DATE'
		)
BEGIN
	CREATE NONCLUSTERED INDEX IDX_CONTACT_DATE ON HNO_NOTE_TEXT (PAT_ENC_CSN_ID) INCLUDE (
		PAT_ID
		,NOTE_ID
		,CONTACT_DATE
		,NOTE_TYPE
		)
END


