/* The purpose of this SQL file is to demonstrate how a cohort can be specified
 * for an i2b2 project within the context of the S.O.F.A.
 */

use <child>i2b2demodata;


IF NOT EXISTS
	(SELECT * FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('PROVIDERS'))
	BEGIN
		CREATE TABLE PROVIDERS([PROV_ID] VARCHAR(15));
	END

TRUNCATE TABLE PROVIDERS;

INSERT INTO PROVIDERS ([PROV_ID])
select    distinct     PROV_ID 
from EPIC_PROVIDERS_TABLE

--Create/truncate MRNs table
IF NOT EXISTS
    (SELECT * FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('MRNs'))
    BEGIN
        CREATE TABLE MRNs([MRN] VARCHAR(50));
    END
TRUNCATE TABLE MRNs;

--Store MRNs of patients
INSERT INTO MRNs
(MRN)
select distinct MRN from EPIC_EMPI_TABLE


--Create/truncate patients table
IF NOT EXISTS
    (SELECT * FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('PATIENTS'))
    BEGIN
        CREATE TABLE PATIENTS([PAT_ID] VARCHAR(15));
    END
TRUNCATE TABLE PATIENTS;

--Store the PAT_IDs based on MRNs found
INSERT INTO PATIENTS
(PAT_ID)
SELECT DISTINCT PAT_ID FROM IDENTITY_ID


IF NOT EXISTS (
		SELECT *
		FROM sys.indexes
		WHERE NAME = 'IDX_PATS'
			AND object_id = OBJECT_ID('PATIENTS')
		)
	CREATE NONCLUSTERED INDEX idx_pats ON [dbo].[PATIENTS] ([PAT_ID])


--Create/truncate irbs table
IF NOT EXISTS
    (SELECT * FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('IRBS'))
    BEGIN
        CREATE TABLE IRBS([PROTOCOL] VARCHAR(15));
    END
TRUNCATE TABLE IRBS;

--Store the IRBs based on the providers
INSERT INTO IRBS
(PROTOCOL)
VALUES(
''
)


IF NOT EXISTS
	(SELECT * FROM SYS.TABLES WHERE OBJECT_ID = OBJECT_ID('REDCAP_PROJECTS'))
	BEGIN
		CREATE TABLE dbo.REDCAP_PROJECTS([PROJ_ID] VARCHAR(15));
	END

TRUNCATE TABLE REDCAP_PROJECTS;
